# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18xiWFhG_9tiFHOmydYcibTnHNjHdSb-Q

BANK ANALYSIS
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import plotly.express as px

df = pd.read_excel('financial_loan_data_excel.xlsx')

df.head()

print(df.shape)

print(df.head)

print(df.dtypes)

print(df.describe)

print(df.shape)

print(df.info)

total_loan_application = df['id'].count()
print(total_loan_application)

"""#MTD Latest"""

latest_issue_date = df['issue_date'].max()
latest_year = latest_issue_date.year
latest_month = latest_issue_date.month

mtd_data = df[(df['issue_date'].dt.year == latest_year) & (df['issue_date'].dt.month == latest_month)]
mtd_loan_applications = mtd_data['id'].count()

print( f"Latest issue date: {latest_issue_date}")
print(  f"Total loan applications in the MTD: {mtd_loan_applications}")

"""#Total Funded Amount

"""

total_funded_amount = df['loan_amount'].sum()
total_funded_amount_millions = total_funded_amount / 1_000_000

print(f"Total Funded Amount: ${total_funded_amount_millions:.2f}M")

"""#MTD Funded amount"""

latest_issue_date = df['issue_date'].max()
latest_year = latest_issue_date.year
latest_month = latest_issue_date.month

mtd_data = df[(df['issue_date'].dt.year == latest_year) & (df['issue_date'].dt.month == latest_month)]
mtd_total_funded_amount = mtd_data['loan_amount'].sum()
mtd_total_funded_amount = mtd_total_funded_amount/1000000
print( f"Latest issue date: {latest_issue_date}")
print(f"Total amount funded in the MTD: ${mtd_total_funded_amount:,.2f}M")

"""#Total Amount received"""

total_amount_received= df['total_payment'].sum()
total_amount_received_millions = total_amount_received/1_000_000

print(f"Total Received Amount: ${total_amount_received_millions:.2f}M")

"""MTD Total Amount Received"""

latest_issue_date = df['issue_date'].max()
latest_year = latest_issue_date.year
latest_month = latest_issue_date.month

mtd_data = df[(df['issue_date'].dt.year == latest_year) & (df['issue_date'].dt.month == latest_month)]
mtd_total_amount_received = mtd_data['total_payment'].sum()
mtd_total_amount_received = mtd_total_amount_received/1000000
print( f"Latest issue date: {latest_issue_date}")
print(f"Total amount received in the MTD: ${mtd_total_amount_received:,.2f}M")

"""#Average Interest Rate"""

interest_rate= df['int_rate'].mean()
interest_rate = interest_rate*100

print(f"Average Interest Rate: {interest_rate:.2f}%")

"""#Average DTI"""

Average_DTI= df['dti'].mean()
Average_DTI = Average_DTI*100

print(f"Average DTI: {Average_DTI:.2f}%")

"""#Good Loan Metrics"""

good_loans = df[df['loan_status'].isin(["Fully Paid", "Current"])]
total_loan_application = df['id'].count()

good_loan_applications = good_loans['id'].count()
good_loans_funded_amount = good_loans['loan_amount'].sum()
good_loan_received = good_loans['total_payment'].sum()


good_loans_funded_amount_millions = good_loans_funded_amount/1000000
good_loan_received_millions = good_loan_received/1000000

good_loan_percentage = (good_loan_applications / total_loan_application) * 100
print(f"Good loan applications: {good_loan_applications:,}")
print(f"Good loans funded amount: ${good_loans_funded_amount_millions:,.2f}M")
print(f"Good loan received: ${good_loan_received_millions:,.2f}M")


print(f"Good loan percentage: {good_loan_percentage:.2%}")

"""#Bad Loan Metrics"""

# Bad loans (Charged Off)
bad_loans = df[df['loan_status'].isin(["Charged Off"])]

bad_loan_applications = bad_loans['id'].count()
bad_loans_funded_amount = bad_loans['loan_amount'].sum()
bad_loan_received = bad_loans['total_payment'].sum()

bad_loans_funded_amount_millions = bad_loans_funded_amount / 1_000_000
bad_loan_received_millions = bad_loan_received / 1_000_000

bad_loan_percentage = (bad_loan_applications / total_loan_application) * 100

print(f"Bad loan applications: {bad_loan_applications:,}")
print(f"Bad loans funded amount: ${bad_loans_funded_amount_millions:,.2f}M")
print(f"Bad loan received: ${bad_loan_received_millions:,.2f}M")
print(f"Bad loan percentage: {bad_loan_percentage:,.2f}%")

"""#monthly trend by issue date"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ---------- Prep (run once) ----------
df = df.copy()
df['issue_date'] = pd.to_datetime(df['issue_date'], errors='coerce')

# Millions helper
to_m = lambda s: s / 1_000_000

# Clean 'term' → numeric months
df['term_months'] = pd.to_numeric(df['term'].astype(str).str.extract(r'(\d+)')[0], errors='coerce')

# Normalize employment length to a fixed order
emp_order = ['< 1 year','1 year','2 years','3 years','4 years','5 years',
             '6 years','7 years','8 years','9 years','10+ years','Unknown']
def normalize_emp(x):
    s = str(x).strip()
    if s.startswith('<'): return '< 1 year'
    if '10' in s: return '10+ years'
    n = pd.to_numeric(pd.Series(s).str.extract(r'(\d+)')[0], errors='coerce').iloc[0]
    if pd.isna(n): return 'Unknown'
    return '1 year' if int(n)==1 else f'{int(n)} years'
df['emp_length_clean'] = df['emp_length'].apply(normalize_emp)
df['emp_length_clean'] = pd.Categorical(df['emp_length_clean'], categories=emp_order, ordered=True)

monthly = (
    df.dropna(subset=['issue_date'])
      .assign(month=lambda x: x['issue_date'].dt.to_period('M').dt.to_timestamp())
      .groupby('month', as_index=False)
      .agg(applications=('id','count'),
           funded=('loan_amount','sum'),
           received=('total_payment','sum'))
)
monthly['funded_m'] = to_m(monthly['funded'])
monthly['received_m'] = to_m(monthly['received'])

# 1A. Applications (line)
plt.figure()
plt.plot(monthly['month'], monthly['applications'], marker='o')
plt.title('Monthly Loan Applications')
plt.xlabel('Month'); plt.ylabel('Applications')
plt.xticks(rotation=45, ha='right'); plt.tight_layout(); plt.show()

# 1B. Funded amount ($M) (area+line)
plt.figure()
plt.fill_between(monthly['month'], monthly['funded_m'], alpha=0.25)
plt.plot(monthly['month'], monthly['funded_m'], linewidth=2)
plt.title('Total Funded Amount by Month ($M)')
plt.xlabel('Month'); plt.ylabel('$M')
plt.xticks(rotation=45, ha='right'); plt.tight_layout(); plt.show()

by_state = (df.groupby('address_state', as_index=False)
              .agg(applications=('id','count'))
              .sort_values('applications', ascending=False)
              .head(20))
plt.figure()
plt.bar(by_state['address_state'], by_state['applications'])
plt.title('Loan Applications by State (Top 20)')
plt.xlabel('State'); plt.ylabel('Applications')
plt.xticks(rotation=45, ha='right'); plt.tight_layout(); plt.show()

term_dist = (df.dropna(subset=['term_months'])
               .groupby('term_months', as_index=False)
               .agg(applications=('id','count'))
               .sort_values('term_months'))
labels = term_dist['term_months'].astype(int).astype(str) + ' mo'
vals = term_dist['applications'].values
plt.figure()
plt.pie(vals, labels=labels, startangle=90, autopct='%1.1f%%',
        wedgeprops={'width':0.4})
plt.gca().set_aspect('equal')
plt.title('Loan Term Distribution (Applications)')
plt.tight_layout(); plt.show()

by_emp = (df.groupby('emp_length_clean', as_index=False)
            .agg(applications=('id','count'))
            .sort_values('emp_length_clean'))
plt.figure()
plt.bar(by_emp['emp_length_clean'].astype(str), by_emp['applications'])
plt.title('Applications by Employment Length')
plt.xlabel('Employment Length'); plt.ylabel('Applications')
plt.xticks(rotation=45, ha='right'); plt.tight_layout(); plt.show()

home = (df.groupby('home_ownership', as_index=False)
          .agg(applications=('id','count'),
               funded=('loan_amount','sum'),
               received=('total_payment','sum')))
home['funded_m'] = to_m(home['funded'])
home['received_m'] = to_m(home['received'])

heat = home[['home_ownership','applications','funded_m','received_m']].set_index('home_ownership')
plt.figure()
im = plt.imshow(heat.values, aspect='auto')
plt.title('Home Ownership — Apps / Funded $M / Received $M')
plt.xlabel('Metric'); plt.ylabel('Home Ownership')
plt.xticks(ticks=range(heat.shape[1]), labels=heat.columns, rotation=45, ha='right')
plt.yticks(ticks=range(heat.shape[0]), labels=heat.index)
plt.colorbar(im); plt.tight_layout(); plt.show()

by_purpose = (df.groupby('purpose', as_index=False)
                .agg(applications=('id','count'))
                .sort_values('applications', ascending=False)
                .head(15))
by_purpose = by_purpose.sort_values('applications')  # for nice ascending barh
plt.figure()
plt.barh(by_purpose['purpose'], by_purpose['applications'])
plt.title('Loan Applications by Purpose (Top 15)')
plt.xlabel('Applications'); plt.ylabel('Purpose')
plt.tight_layout(); plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ---------- Prep ----------
df = df.copy()
df['issue_date'] = pd.to_datetime(df['issue_date'], errors='coerce')
df = df.dropna(subset=['issue_date'])

# Helpers
to_m = lambda s: s / 1_000_000
df['term_months'] = pd.to_numeric(df['term'].astype(str).str.extract(r'(\d+)')[0], errors='coerce')

emp_order = ['< 1 year','1 year','2 years','3 years','4 years','5 years',
             '6 years','7 years','8 years','9 years','10+ years','Unknown']
def normalize_emp(x):
    s = str(x).strip().lower()
    if not s or s in ('nan','none'): return 'Unknown'
    if '10' in s or '10+' in s: return '10+ years'
    if '<' in s: return '< 1 year'
    n = pd.to_numeric(pd.Series(s).str.extract(r'(\d+)')[0], errors='coerce').iloc[0]
    if pd.isna(n): return 'Unknown'
    return '1 year' if int(n)==1 else f'{int(n)} years'

df['emp_length_clean'] = pd.Categorical(df['emp_length'].apply(normalize_emp), categories=emp_order, ordered=True)

# ---------- Aggregations ----------
monthly = (
    df.assign(month=df['issue_date'].dt.to_period('M').dt.to_timestamp())
      .groupby('month', as_index=False)
      .agg(applications=('id','count'),
           funded=('loan_amount','sum'),
           received=('total_payment','sum'))
)
monthly['funded_m'] = to_m(monthly['funded'])
monthly['received_m'] = to_m(monthly['received'])

by_state = (df.groupby('address_state', as_index=False)
              .agg(applications=('id','count'))
              .sort_values('applications', ascending=False)
              .head(10))

term_dist = (df.dropna(subset=['term_months'])
               .groupby('term_months', as_index=False)
               .agg(applications=('id','count'))
               .sort_values('term_months'))

by_emp = (df.groupby('emp_length_clean', as_index=False)
            .agg(applications=('id','count'))
            .sort_values('emp_length_clean'))

by_purpose = (df.groupby('purpose', as_index=False)
                .agg(applications=('id','count'))
                .sort_values('applications', ascending=False)
                .head(10))
by_purpose = by_purpose.sort_values('applications')

home = (df.groupby('home_ownership', as_index=False)
          .agg(applications=('id','count'),
               funded=('loan_amount','sum'),
               received=('total_payment','sum')))
home['funded_m'] = to_m(home['funded'])
home['received_m'] = to_m(home['received'])
heat = home[['home_ownership','applications','funded_m','received_m']].set_index('home_ownership')

# ---------- Dashboard (2×3) ----------
fig, axes = plt.subplots(2, 3, figsize=(18, 10))

# (1) Applications by Month
ax = axes[0,0]
ax.plot(monthly['month'], monthly['applications'], marker='o', linewidth=1.8)
ax.set_title('Monthly Loan Applications'); ax.set_ylabel('Applications')
ax.tick_params(axis='x', rotation=45)

# (2) Funded Amount by Month ($M)
ax = axes[0,1]
ax.fill_between(monthly['month'], monthly['funded_m'], alpha=0.25)
ax.plot(monthly['month'], monthly['funded_m'], linewidth=1.8)
ax.set_title('Total Funded Amount by Month ($M)'); ax.set_ylabel('$M')
ax.tick_params(axis='x', rotation=45)

# (3) Applications by State (Top 10)
ax = axes[0,2]
ax.bar(by_state['address_state'], by_state['applications'])
ax.set_title('Applications by State (Top 10)'); ax.set_xlabel('State'); ax.set_ylabel('Applications')
ax.tick_params(axis='x', rotation=45)

# (4) Applications by Loan Term
ax = axes[1,0]
ax.bar(term_dist['term_months'].astype(int).astype(str), term_dist['applications'])
ax.set_title('Applications by Loan Term'); ax.set_xlabel('Term (months)'); ax.set_ylabel('Applications')

# (5) Applications by Employment Length
ax = axes[1,1]
ax.bar(by_emp['emp_length_clean'].astype(str), by_emp['applications'])
ax.set_title('Applications by Employment Length'); ax.set_xlabel('Employment Length'); ax.set_ylabel('Applications')
ax.tick_params(axis='x', rotation=45)

# (6) Home Ownership — Apps / Funded $M / Received $M (Heatmap)
ax = axes[1,2]
im = ax.imshow(heat.values, aspect='auto')
ax.set_title('Home Ownership — Apps / Funded $M / Received $M')
ax.set_xlabel('Metric'); ax.set_ylabel('Home Ownership')
ax.set_xticks(range(heat.shape[1])); ax.set_xticklabels(heat.columns, rotation=45, ha='right')
ax.set_yticks(range(heat.shape[0])); ax.set_yticklabels(heat.index)
fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

plt.tight_layout()
plt.show()